[project]
name = "python-starter-kit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "coverage>=7.14.0",
    "pyright>=1.1.409",
    "ruff>=0.15.12",
]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
fail_under = 100
show_missing = true
exclude_also = [
    "if __name__ == .__main__.:",
]
